import {describe,it,expect} from 'vitest';
import { calculateModels,presentValue,realOptionCall } from '../../src/lib/valuation/calculate';
import { DEFAULT_ASSUMPTIONS, MODEL_IDS, type Fundamentals } from '../../src/lib/valuation/types';
import { validateDocument,validateFundamentals } from '../../src/lib/valuation/validate';
const date='2026-09-30';
function fixture():Fundamentals {
 const values:Record<string,number>={shares:10,eps:5,forwardEps:6,dividendPerShare:2,revenue:1000,netIncome:50,ebit:100,ebitda:120,taxRate:.25,depreciation:20,capex:30,workingCapitalChange:5,debt:200,cash:50,minority:0,preferred:0,operatingCashFlow:90,netBorrowing:5,bookEquity:500,payoutRatio:.4,investedCapital:650,taxShieldPv:50,distressCostPv:10,expectedEpsGrowth:.1,goodwill:20,intangibles:30,assetMarketValue:900,liabilities:200,receivables:100,inventory:100,ppe:200,liquidationCosts:10,replacementAssetValue:1000,adjustedNetAssets:500,weightedAdjustedEarnings:60,baseEquityValue:500,optionAsset:100,optionInvestment:80,riskFreeRate:.04,optionVolatility:.3,optionYears:3,corporateCostPv:20,targetForwardPe:15,targetCape:20,targetEvEbit:10,targetEvEbitda:8,targetPs:2,targetEvSales:3,targetPb:1.5,targetPcf:10,targetPtbv:2};
 const facts=Object.fromEntries(Object.entries(values).map(([key,value])=>[key,{value,period:date,unit:(['shares'].includes(key)?'shares':['eps','forwardEps','dividendPerShare'].includes(key)?'perShare':['taxRate','payoutRatio','expectedEpsGrowth','riskFreeRate','optionVolatility'].includes(key)?'fraction':key.startsWith('target')||key==='optionYears'?'ratio':'currency') as 'currency'}]));
 return {ticker:'TEST',provider:'stockrow',url:'https://stockrow.com/TEST',fetchedAt:date,currency:'USD',statementDate:date,price:50,priceAsOf:date,facts,annual:{pe:[10,12,14].map((value,i)=>({value,period:`${2025-i}-09`,unit:'ratio'})),realEps:Array.from({length:10},(_,i)=>({value:4,period:`${2025-i}-09`,unit:'perShare'}))},industry:'Software',peers:[{ticker:'A',industry:'Software',pe:10},{ticker:'B',industry:'Software',pe:12},{ticker:'C',industry:'Software',pe:14}],segments:[{name:'One',ebit:50,multiple:10},{name:'Two',ebit:40,multiple:8}]};
}
const run=(d=fixture())=>calculateModels(d,DEFAULT_ASSUMPTIONS,'2026-10-03');
describe('Independent valuation methods',()=>{
 it('evaluates every requested model with complete justified inputs',()=>{const r=run();expect(r.map(x=>x.id)).toEqual([...MODEL_IDS]);expect(r.filter(x=>x.status==='available')).toHaveLength(26);expect(r.every(x=>Number.isFinite(x.value)&&x.used.length>0)).toBe(true);});
 it('uses correct cash-flow recipients and subtracts enterprise claims exactly once',()=>{const r=Object.fromEntries(run().map(x=>[x.id,x]));expect(r.fcff.value).toBeCloseTo((presentValue(60,.1,.03,.02,5)-150)/10);expect(r.fcfe.value).toBeCloseTo(presentValue(65,.1,.03,.02,5)/10);expect(r.ddm.value).toBeCloseTo(25.5);expect(r.apv.value).toBeCloseTo((presentValue(60,.1,.03,.02,5)+50-10-150)/10);});
 it('uses a two-stage dividend projection and not the Gordon-only result',()=>{const r=run();expect(r.find(x=>x.id==='ddm2')?.value).toBeCloseTo(presentValue(2,.1,.03,.02,5));});
 it('calculates historical, peer, forward, PEG, CAPE and enterprise multiples',()=>{const r=Object.fromEntries(run().map(x=>[x.id,x]));expect(r.peHistory.value).toBe(60);expect(r.peIndustry.value).toBe(60);expect(r.forwardPe.value).toBe(90);expect(r.peg.value).toBe(50);expect(r.cape.value).toBe(80);expect(r.evEbit.value).toBe(85);expect(r.evEbitda.value).toBe(81);expect(r.ps.value).toBe(200);expect(r.evSales.value).toBe(285);expect(r.pb.value).toBe(75);expect(r.pcf.value).toBe(90);expect(r.ptbv.value).toBe(90);});
 it('requires real specialist inputs instead of applying market multiples to projects',()=>{const r=Object.fromEntries(run().map(x=>[x.id,x]));expect(r.nav.value).toBe(70);expect(r.liquidation.value).toBe(6.5);expect(r.reproduction.value).toBe(80);expect(r.stuttgart.value).toBeCloseTo(54.4);expect(r.sotp.value).toBe(65);expect(r.realOption.value).toBeCloseTo((500+realOptionCall(100,80,.04,.3,3))/10);});
 it('matches a known Black-Scholes call and respects project inputs',()=>{expect(realOptionCall(100,100,.05,.2,1)).toBeCloseTo(10.4506,3);expect(()=>realOptionCall(100,100,.05,0,1)).toThrow();});
 it('reports missing data across all models without substituting zeros',()=>{const d=fixture();d.facts={};d.annual={};d.peers=[];d.segments=[];const r=run(d);expect(r.every(x=>x.status==='missing'&&x.value==null&&x.missing.length>0)).toBe(true);});
 it('rejects perpetuities when discount rate does not exceed terminal growth',()=>{const r=calculateModels(fixture(),{...DEFAULT_ASSUMPTIONS,wacc:.02,costEquity:.02},'2026-10-03');for(const id of ['fcff','fcfe','ddm','ddm2','residual','eva'])expect(r.find(x=>x.id===id)?.status).toBe('invalid');});
 it('does not price non-paying, loss-making or stale stocks as ordinary mature firms',()=>{const d=fixture();d.facts.dividendPerShare.value=0;d.facts.eps.value=-1;expect(run(d).find(x=>x.id==='ddm')?.status).toBe('invalid');expect(run(d).find(x=>x.id==='peHistory')?.status).toBe('invalid');d.statementDate='2020-01-01';expect(run(d).every(x=>x.status==='stale')).toBe(true);});
 it('requires inflation-adjusted ten-year earnings for CAPE and minimum peer/history coverage',()=>{const d=fixture();d.annual!.realEps!.pop();d.peers!.pop();d.annual!.pe.pop();const r=run(d);for(const id of ['cape','peIndustry','peHistory'])expect(r.find(x=>x.id===id)?.status).toBe('missing');});
 it('requires distinct identified peers and discards non-period text',()=>{const d=fixture();d.peers=[d.peers![0],d.peers![0],d.peers![1]];expect(run(d).find(x=>x.id==='peIndustry')?.status).toBe('missing');d.facts.eps.period='session-secret';expect(validateFundamentals(d,'TEST')?.facts.eps).toBeUndefined();});
 it('never mutates source facts or compares an old price as current',()=>{const d=fixture();const before=JSON.stringify(d);run(d);expect(JSON.stringify(d)).toBe(before);d.priceAsOf='2026-01-01';expect(run(d).every(x=>x.upsidePct==null)).toBe(true);});
 it('rejects mixed annual periods and malformed scenario assumptions',()=>{const d=fixture();d.facts.ebit.period='2024-09-30';expect(run(d).find(x=>x.id==='fcff')?.status).toBe('invalid');expect(calculateModels(fixture(),{...DEFAULT_ASSUMPTIONS,years:1.5},'2026-10-03').every(x=>x.status==='invalid')).toBe(true);});
});
describe('Public financial-data boundary',()=>{
 it('strips unexpected raw data and credentials and checks currency/unit/identity',()=>{const raw={...fixture(),cookies:'SECRET',secret:'SECRET',facts:{...fixture().facts,token:{value:123,period:date,unit:'currency'}}};const d=validateFundamentals(raw,'TEST');expect(JSON.stringify(d)).not.toContain('SECRET');expect(d?.facts.token).toBeUndefined();expect(validateFundamentals(raw,'OTHER')).toBeNull();expect(validateFundamentals({...raw,currency:'???'},'TEST')).toBeNull();(raw.facts as Fundamentals['facts']).eps.unit='currency';expect(validateFundamentals(raw,'TEST')?.facts.eps).toBeUndefined();});
 it('rejects credential-bearing URLs and non-provider origins',()=>{for(const url of ['https://stockrow.com/TEST?api_key=secret','https://evil.test','https://user:password@stockrow.com/TEST'])expect(validateFundamentals({...fixture(),url},'TEST')).toBeNull();});
 it('validates document version and drops unknown ticker shapes',()=>{expect(()=>validateDocument({})).toThrow();const d=validateDocument({schemaVersion:1,generatedAt:date,stocks:{TEST:[fixture()],'../secret':[fixture()]}});expect(Object.keys(d.stocks)).toEqual(['TEST']);});
});
