import { useEffect, useMemo, useState } from 'react';
import { useI18n } from '@/hooks/useI18n';
import { calculateModels } from '@/lib/valuation/calculate';
import { validateDocument } from '@/lib/valuation/validate';
import { DEFAULT_ASSUMPTIONS, type Assumptions, type ValuationDocument } from '@/lib/valuation/types';
import { modelLabel, fieldLabel, formulaLabel } from '@/lib/valuation/labels';
import type { FairValueResult } from '@/types/fairValue';

let request:Promise<ValuationDocument>|undefined;let expires=0;
function load(){if(Date.now()>=expires)request=undefined;expires=Date.now()+60000;return request??=(fetch(`${import.meta.env.BASE_URL}data/valuations.json`,{cache:'no-store'}).then(async r=>{if(r.status===404)return{schemaVersion:1,generatedAt:new Date().toISOString(),stocks:{}} as ValuationDocument;if(!r.ok)throw new Error();return validateDocument(await r.json());}).catch(e=>{request=undefined;throw e;}));}
export function FairValuePanel({ticker,fallback}:{ticker:string;fallback?:FairValueResult}) {
 const {language}=useI18n();const de=language==='de';
 const [document,setDocument]=useState<ValuationDocument>();const [failed,setFailed]=useState(false);
 const [provider,setProvider]=useState('');const [a,setA]=useState({...DEFAULT_ASSUMPTIONS});
 useEffect(()=>{let active=true;load().then(d=>{if(active)setDocument(d);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[]);
 useEffect(()=>{setProvider('');setA({...DEFAULT_ASSUMPTIONS});},[ticker]);
 const datasets=(document?.stocks[ticker]??[]).filter(d=>d.provider!=='gurufocus');
 const selected=datasets.find(d=>d.provider===provider)??datasets[0];
 const results=useMemo(()=>selected?calculateModels(selected,a):[],[selected,a]);
 const money=(n:number)=>new Intl.NumberFormat(de?'de-DE':'en-US',{style:'currency',currency:selected?.currency??'USD',maximumFractionDigits:2}).format(n);
 const factValue=(key:string)=>{const f=selected?.facts[key];if(!f)return de?'Belegte Vergleichsreihe':'Attributed comparison series';const formatted=f.unit==='currency'||f.unit==='perShare'?money(f.value):f.unit==='fraction'?new Intl.NumberFormat(de?'de-DE':'en-US',{style:'percent',maximumFractionDigits:2}).format(f.value):new Intl.NumberFormat(de?'de-DE':'en-US',{maximumFractionDigits:4}).format(f.value)+(f.unit==='ratio'&&key!=='optionYears'?' ×':'');return `${formatted} · ${f.period}${f.derived?(de?' (abgeleitet)':' (derived)'):''}`;};
 const controls:[keyof Assumptions,string,string,number,number][]=[
 ['years','Forecast years','Prognosejahre',1,30],['growth','Forecast growth (%)','Prognosewachstum (%)',-50,50],['terminalGrowth','Terminal growth (%)','Ewiges Wachstum (%)',-2,5],['wacc','WACC (%)','Gesamtkapitalkosten (%)',1,50],['costEquity','Cost of equity (%)','Eigenkapitalkosten (%)',1,50],['unleveredRate','Unlevered rate (%)','Diskontsatz ohne Schulden (%)',1,50],['marketYield','Market yield (%)','Vergleichs-Marktzins (%)',.1,30],['targetPeg','Target PEG','Ziel-PEG',.1,5],['receivableRecovery','Receivables recovery (%)','Forderungsverwertung (%)',0,100],['inventoryRecovery','Inventory recovery (%)','Vorratsverwertung (%)',0,100],['ppeRecovery','PPE recovery (%)','Sachanlagenverwertung (%)',0,100]];
 const groups=[['Cash flow & dividends','Cashflow & Dividenden',0,7],['Earnings multiples','Gewinnmultiplikatoren',7,14],['Sales & balance sheet multiples','Umsatz- & Bilanzmultiplikatoren',14,20],['Asset values','Substanzwerte',20,23],['Special methods','Spezialverfahren',23,26]] as const;
 if (!selected && fallback) return <section className="valuation-panel"><h3 className="text-sm font-bold">{de?'Fair Value · 26 Bewertungsmodelle':'Fair value · 26 valuation models'}</h3><p className="mt-2 text-xs text-secondary">{de?'Modellabdeckung der aktuellen Aktienanalyse. Spezielle Eingaben und historische Reihen fehlen teilweise.':'Model coverage from the current stock analysis. Specialist inputs and historical series are partially missing.'}</p><div className="valuation-models mt-3">{fallback.models.map(m=><details key={m.name}><summary><span>{m.name}</span><span>{m.value == null ? (de?'Eingaben fehlen':'Missing inputs') : new Intl.NumberFormat(de?'de-DE':'en-US',{style:'currency',currency:fallback.currency}).format(m.value)}</span></summary><p className="text-xs mt-2">{m.reason || (de?'Berechnet aus den belegten Eingaben und den ausgewiesenen Modellannahmen.':'Calculated from attributed inputs and disclosed assumptions.')}</p></details>)}</div></section>;
 return <section className="valuation-panel" aria-label={de?'Fair Value':'Fair value'}>
  <div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-bold uppercase tracking-wide">{de?'Fair Value · 26 Bewertungsmodelle':'Fair value · 26 valuation models'}</h3>{selected&&<span className="text-xs text-secondary">{results.filter(r=>r.status==='available').length} / 26 {de?'berechenbar':'calculable'}</span>}</div>
  {!document&&!failed?<p className="mt-3 text-sm text-secondary">{de?'Finanzdaten werden geladen …':'Loading financial data…'}</p>:failed?<p className="mt-3 text-sm text-secondary">{de?'Die Finanzdaten konnten nicht geladen werden. Bitte versuche es später erneut.':'Financial data could not be loaded. Please try again later.'}</p>:!selected?<p className="mt-3 text-sm text-secondary">{de?'Für diese Aktie liegen noch keine ausreichenden belegten Finanzdaten vor. Es wird kein Fair Value geschätzt.':'Verified financial inputs are not yet available for this stock. No fair value is estimated.'}</p>:<>
   <p className="mt-2 text-sm text-secondary">{de?'Separater Szenariorechner mit veränderbaren Annahmen und konstanter Wachstumsprojektion. Der gemeinsame zentrale Fair Value verwendet eine zehnjährige Wachstumsabflachung; die unterschiedlichen Annahmen können andere Werte ergeben. Modellwerte je Aktie, keine Kursziele. Fehlende Eingaben werden nicht ersetzt. Bewertung und Annahmen verändern weder den Signal-Score noch das Portfolio.':'Separate scenario calculator with editable assumptions and constant growth. Shared central fair value uses a ten-year growth fade; different assumptions can produce different values. Model values per share, not price targets. Missing inputs are not substituted. Valuation and assumptions do not change signal scores or portfolios.'}</p>
   <div className="valuation-source mt-3 flex flex-wrap items-center gap-3 text-xs"><label>{de?'Datenbasis':'Dataset'} <select className="input ml-2 !w-auto" value={selected.provider} onChange={e=>setProvider(e.target.value)}>{datasets.map(d=><option key={d.provider} value={d.provider}>{d.provider==='gurufocus'?'GuruFocus':d.provider==='tikr'?'TIKR':d.provider==='macrotrends'?'Macrotrends':'Stockrow'}</option>)}</select></label><a href={selected.url} target="_blank" rel="noreferrer" className="underline">{de?'Quelle ansehen':'View source'}</a><span>{selected.basis?(de?'TTM beobachtet am ':'TTM observed on '):(de?'Jahresabschluss: ':'Annual period: ')}{selected.statementDate}</span><span>{de?'Abgerufen: ':'Retrieved: '}{selected.fetchedAt.slice(0,10)}</span>{selected.price!=null&&<span>{de?'Vergleichskurs: ':'Comparison price: '}{money(selected.price)} · {selected.priceAsOf}</span>}</div>
   {selected.basis&&<p className="mt-2 text-xs text-secondary">{de?'Gewinnbasis: verwässerter TTM-Gewinn; die Wachstumsprognose bereinigt Sondereffekte.':'Earnings basis: diluted TTM EPS; the growth forecast excludes non-recurring items.'}</p>}
   <details className="valuation-assumptions mt-3"><summary>{de?'Modellannahmen bearbeiten':'Edit model assumptions'}</summary><p className="mt-2 text-xs text-secondary">{de?'Startannahmen sind Szenariowerte, keine beobachteten Marktdaten. Zukunfts-Cashflows werden mit konstantem Wachstum projiziert; EVA unterstellt konstanten ROIC; das Residualeinkommensmodell schreibt das letzte Residualeinkommen mit ewigem Wachstum fort. Historische Multiplikatoren sind Mittelwerte von bis zu 10 positiven Jahreswerten (mindestens 3). Realoptionen benötigen Projektvolatilität, nicht die Volatilität der Aktie.':'Defaults are scenario assumptions, not observed market data. Future cash flows use constant growth; EVA assumes constant ROIC; residual income capitalizes next-period residual income at perpetual growth. Historical multiples average up to 10 positive annual observations (at least 3). Real options require project volatility, not stock volatility.'}</p><div className="valuation-controls">{controls.map(([key,en,label,min,max])=>{const percent=!['years','targetPeg'].includes(key);return <label key={key}><span>{de?label:en}</span><input className="input" type="number" step={key==='years'?1:.1} min={min} max={max} value={Number((a[key]*(percent?100:1)).toFixed(3))} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n))setA(old=>({...old,[key]:n/(percent?100:1)}));}} /></label>;})}</div><button className="btn mt-3" onClick={()=>setA({...DEFAULT_ASSUMPTIONS})}>{de?'Annahmen zurücksetzen':'Reset assumptions'}</button></details>
   {groups.map(([en,label,start,end])=><div key={en} className="mt-4"><h4 className="mb-2 text-xs font-bold uppercase tracking-wide text-secondary">{de?label:en}</h4><div className="valuation-models">{results.slice(start,end).map(r=><details key={r.id} data-model={r.id}><summary><span>{modelLabel(r.id,language)}</span><span className="valuation-value">{r.value!=null?money(r.value):de?(r.status==='missing'?'Eingaben fehlen':r.status==='stale'?'Datierung unzureichend':'Nicht anwendbar'):(r.status==='missing'?'Missing inputs':r.status==='stale'?'Insufficient dating':'Not applicable')}{r.upsidePct!=null&&<small>{r.upsidePct>=0?'+':''}{r.upsidePct.toFixed(1)}% {de?'zum Vergleichskurs':'vs comparison price'}</small>}</span></summary><div className="valuation-model-detail"><p className="valuation-formula">{formulaLabel(r.formula,language)}</p>{r.missing.length>0&&<p>{de?'Benötigt bzw. zu prüfen: ':'Required or needs review: '}{r.missing.map(k=>fieldLabel(k,language)).join(' · ')}</p>}{r.used.length>0&&<dl>{r.used.map(k=><div key={k}><dt>{fieldLabel(k,language)}</dt><dd>{factValue(k)}</dd></div>)}</dl>}</div></details>)}</div></div>)}
  </>}
 </section>;
}
